### ISSUE TITLE
error 403

### ISSUE THREAD

**Issue by AfsalAfzz-Pro** [evildevill/Article-Summarizer#1]
i am getting an error 403 when i call the api for requests and when i cicked the error link i got a response of 'invalid api key. view rapid api documentation' which leads me to another url which says page not found. i am very sure that i used the correct api key

**Comment by evildevill** [comment]
@AfsalAfzz-Pro

Hi, the tool is working fine. I hope you are using the correct API key for this.
<br>
![Screenshot 2023-05-04 181109](https://user-images.githubusercontent.com/66058079/236215368-89a0fc7f-0ff2-432d-8ca6-1b1411dc5e03.png)
